[preface]
[[_preface]]
== はじめに


=== この文書の目的

[.lead]
この文書は、ソフトウェアの開発にモデリングツールを使う方法などについて独習するためのチュートリアルです。

このチュートリアルは、ソフトウェアの開発に、UMLを使って描いたモデルが役に立つことを実感する機会を提供することを目的としています。
主に、これからソフトウェア開発にモデル図を使うことについて学ぶみなさんを対象にしています。
また、モデリングツールを使うことにも慣れてもらえるよう、「*{astah} Professional*」使って演習します。

=== 対象・目標

==== チュートリアルの対象者

このチュートリアルは、次のような方を対象者と想定しています。

.チュートリアルの対象者
* モデリングやUMLについてこれから学ぼうとしているみなさん
* ソフトウェア開発工程は知っているが、まだモデル図を活用していないみなさん
* 分析・設計・テストなどソフトウェアの開発に携わっているみなさん
- UMLモデルを活かしてWebアプリケーションを作ってみたい

==== チュートリアルの目標

みなさんがチュートリアル終了後に次のような人になっていることを、このチュートリアルの目標としています。

.チュートリアルの目標（人物像）
* 開発工程のどこでどのモデル図を使えばよいか知っている（知っている人になる）。
* 「開発にはモデルがあったほうがいい」と考えている。
* 自分だけでなく他の人にもモデリングを勧めたいと考えている。

<<<<

=== アイコンの説明

本文中では、次のようなアイコンを用いています。

NOTE: 告知。みなさんが覚えておくとよい追加情報など。

TIP: ティップス。覚えておくと便利なちょっとしたヒントやコツ。

IMPORTANT: 重要。間違えたり見落としたりすると期待通りの結果が得られない設定や操作など。

CAUTION: 注意。気をつけないと問題の発生につながるようなことがら。

WARNING: 警告。守らないと破損や怪我などにつながる可能性のあることがら。


=== Webアプリ版について

このチュートリアルは、『UML初学者向けチュートリアル: モデルを使ってソフトウェアを開発しよう』のWebアプリ版です。
ここでは、元になったチュートリアルとWebアプリ版の関係を説明します。

==== Webアプリ版の目標

元になったチュートリアルでは、UMLモデリングの基礎を学びながら、UMLモデルからRubyでコマンドラインアプリケーションを作ります。
それに対して、このチュートリアルは、Webアプリケーションを開発することを目的としています。

題材は、元になったチュートリアルと同じボーリングのスコア計算システムです。

1. モデルで設計する（クラス図、状態機械図など）
2. モデルからコードを得る方法を規定する
3. Webアプリケーションとして実装する
4. データベースで永続化する


==== 元のチュートリアルとの相違点

このWeb版では、もとのチュートリアルで作成したのと同じスコア計算方法を活用しながら、Webアプリケーションとして実装する方法を学びます。

* ビジネスロジック（スコア計算）は共通
* モデル駆動開発のアプローチは共通
* Webアプリケーション特有の設計を追加
